org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
enabled_platforms=fabric,forge
mod_id=exposure
archives_name=exposure
mod_name=Exposure
mod_version=1.9.21
mod_release_type=release
mod_license=MIT
maven_group=io.github.mortuusars.exposure
mod_authors=mortuusars
mod_description=Camera mod with focus on process and aesthetics.
mod_page=https://www.curseforge.com/minecraft/mc-mods/exposure
mod_github=https://github.com/mortuusars/Exposure
mod_issues=https://github.com/mortuusars/Exposure/issues
mod_curseforge_project_id=871755
mod_modrinth_project_id=hB899VmG
# Base
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.20.2)
supported_minecraft_versions=1.20,1.20.1
parchment_version=1.20.1:2023.09.03
# Fabric
fabric_loader_version=0.16.9
fabric_api_version=0.92.2+1.20.1
# Forge
forge_version=1.20.1-47.2.0
forge_version_range=[47,)
forge_loader_version_range=[4,)
jade_forge_id=6855440
realcamera_forge_id=7082366
# Dependencies
forge_config_api_port_version=8.0.1
jei_version=15.20.0.112
rhino_version=2101.2.6-build.66
kubejs_version=2001.6.5-build.7
jupiterVersion=5.11.3
# Create
create_version_range=[6.0.7,)
create_version_range_reason=Exposure 1.9.12+ needs Create 6.0.7+ for sequenced film developing recipes to work. Downgrade Exposure if you want to use older Create versions.
create_version = 6.0.8-289
ponder_version = 1.0.91
flywheel_version = 1.0.5
registrate_version = MC1.20-1.3.3
